"""Publish what the log collector needs to reach your clusters.

bnkscope collects pod logs by *pulling* them through the Kubernetes API — the
same mechanism as the live log viewer — rather than injecting anything. That is
not a stylistic preference: a container's stdout is captured by the runtime into
``/var/log/pods`` on the **node**, so an ephemeral container cannot read its
siblings' output, and adding a hostPath is not something an ephemeral container
can do either. Injection was never available for logs.

Pulling turns out to be better anyway. It survives a TMM pod restart, which
ephemeral metric injection does not.

The collector is Grafana Alloy (``loki.source.kubernetes``), which does the
tailing, backoff and reconnect work properly. What it cannot do is find your
clusters: bnkscope's registered clusters live encrypted in its own database, and
only some of them are in the operator's ``~/.kube/config`` — on the development
machine this module was written against, one of three. A collector mounting the
host kubeconfig would have covered a third of the estate and looked healthy.

So this module writes, into a volume shared with Alloy:

  ``clusters/<id>.yaml``   a portable kubeconfig per reachable cluster
  ``config.alloy``         a generated Alloy config, one tail block per cluster

and pokes Alloy's reload endpoint. Credentials that expire (EKS, GKE) are
refreshed by rewriting the files on a schedule — see ``jobs/``.
"""

import logging
import os
from pathlib import Path
from typing import Any

import requests
from sqlalchemy.orm import Session

from core.encryption import decrypt_value
from models import KubernetesCluster

logger = logging.getLogger(__name__)

#: Shared with the Alloy container (read-only there).
TELEMETRY_DIR = Path(os.getenv("BNKSCOPE_TELEMETRY_DIR", "/telemetry"))
CLUSTERS_DIR = TELEMETRY_DIR / "clusters"
ALLOY_CONFIG = TELEMETRY_DIR / "config.alloy"

#: Alloy's own HTTP server, for reloading after a rewrite.
ALLOY_RELOAD_URL = os.getenv(
    "BNKSCOPE_ALLOY_RELOAD_URL", "http://127.0.0.1:12345/-/reload"
)
LOKI_PUSH_URL = os.getenv(
    "BNKSCOPE_LOKI_PUSH_URL", "http://127.0.0.1:3100/loki/api/v1/push"
)

def _alloy_id(cluster: KubernetesCluster) -> str:
    """A component label Alloy accepts: letters, digits and underscores."""
    return f"c{cluster.id}"


def _kubeconfig_for(cluster: KubernetesCluster) -> str | None:
    """The cluster's stored kubeconfig, decrypted and normalised.

    Returns None rather than raising: one unreadable cluster must not stop the
    others being collected.
    """
    if not cluster.kubeconfig_encrypted:
        return None
    try:
        raw = decrypt_value(cluster.kubeconfig_encrypted)
    except Exception:  # noqa: BLE001 — a bad row is a skip, not a crash
        logger.warning("Could not decrypt kubeconfig for cluster %s", cluster.name)
        return None
    if not raw:
        return None

    from services.kubeconfig_normalizer import (  # local: avoids an import cycle
        NormalizationSource,
        normalize_kubeconfig,
    )

    try:
        return normalize_kubeconfig(raw, source=NormalizationSource.INTERNAL_REREAD)
    except Exception:  # noqa: BLE001
        logger.warning("Kubeconfig for cluster %s is not portable", cluster.name)
        return None


def publish_kubeconfigs(db: Session) -> list[KubernetesCluster]:
    """Write one kubeconfig per collectable cluster. Returns those written."""
    CLUSTERS_DIR.mkdir(parents=True, exist_ok=True)

    clusters = db.query(KubernetesCluster).all()
    written: list[KubernetesCluster] = []
    keep: set[str] = set()

    for cluster in clusters:
        content = _kubeconfig_for(cluster)
        if content is None:
            continue
        path = CLUSTERS_DIR / f"{cluster.id}.yaml"
        # 0600: this is a credential, on a volume another container reads.
        path.write_text(content)
        path.chmod(0o600)
        keep.add(path.name)
        written.append(cluster)

    # A cluster that was removed should stop being collected, and its
    # credentials should not linger on disk.
    for stale in CLUSTERS_DIR.glob("*.yaml"):
        if stale.name not in keep:
            stale.unlink(missing_ok=True)
            logger.info("Removed stale collector kubeconfig %s", stale.name)

    return written


def render_alloy_config(clusters: list[KubernetesCluster]) -> str:
    """The Alloy river config: one discovery+tail pair per cluster.

    Labels are kept deliberately few. Loki indexes by label, and a label whose
    values churn — a pod name across restarts, an F5 message id — turns one
    stream into thousands. `cluster`, `namespace`, `pod` and `container` are
    what you actually filter on; everything else belongs in the line.
    """
    blocks: list[str] = [
        "// Generated by bnkscope (services/log_collector_service.py).",
        "// Edits here are overwritten whenever the cluster list changes.",
        "",
        'logging {',
        '  level  = "warn"',
        '  format = "logfmt"',
        '}',
        "",
        'loki.write "default" {',
        "  endpoint {",
        f'    url = "{LOKI_PUSH_URL}"',
        "  }",
        "}",
    ]

    for cluster in clusters:
        cid = _alloy_id(cluster)
        kubeconfig = f"{CLUSTERS_DIR}/{cluster.id}.yaml"
        name = cluster.name.replace('"', '\\"')
        blocks += [
            "",
            f"// ---- {name} (cluster id {cluster.id}) ----",
            f'discovery.kubernetes "{cid}" {{',
            '  role            = "pod"',
            f'  kubeconfig_file = "{kubeconfig}"',
            "}",
            "",
            f'discovery.relabel "{cid}" {{',
            f"  targets = discovery.kubernetes.{cid}.targets",
            "  // The cluster this stream came from. Static per block — there",
            "  // is no cluster identity in the Kubernetes API to discover.",
            "  rule {",
            '    target_label = "cluster"',
            f'    replacement  = "{name}"',
            "  }",
            "  rule {",
            '    source_labels = ["__meta_kubernetes_namespace"]',
            '    target_label  = "namespace"',
            "  }",
            "  rule {",
            '    source_labels = ["__meta_kubernetes_pod_name"]',
            '    target_label  = "pod"',
            "  }",
            "  rule {",
            '    source_labels = ["__meta_kubernetes_pod_container_name"]',
            '    target_label  = "container"',
            "  }",
            "}",
            "",
            f'loki.source.kubernetes "{cid}" {{',
            f"  targets    = discovery.relabel.{cid}.output",
            "  forward_to = [loki.process.default.receiver]",
            "",
            "  // Without an explicit client Alloy looks for in-cluster",
            "  // credentials, ignores KUBECONFIG, and fails to start.",
            "  client {",
            f'    kubeconfig_file = "{kubeconfig}"',
            "  }",
            "}",
        ]

    # One shared processing stage: attach the cluster label by target, and pull
    # a severity out of the two formats F5 actually emits.
    blocks += [
        "",
        'loki.process "default" {',
        "  forward_to = [loki.write.default.receiver]",
        "",
        "  // Alloy tails a container from the start of what the runtime still",
        "  // holds, which on a long-lived pod means days of history replayed at",
        "  // startup. Loki rejects anything past its retention window, so",
        "  // without this the first minutes are a wall of 400s and dropped",
        "  // batches. 23h, just inside Loki's 24h, so the two cannot race.",
        "  stage.drop {",
        '    older_than          = "23h"',
        '    drop_counter_reason = "older_than_retention"',
        "  }",
        "",
        "  // TMM writes syslog, and the F5 message id sits *after* the",
        "  // header, not at the start of the line:",
        "  //   <134>Aug 23 20:02:47 host tmm[46]: 01010058:6: audit log: ...",
        "  // Anchoring this at ^ matches nothing at all and leaves every TMM",
        "  // line at level=unknown — which is how it was written the first",
        "  // time, and looked like the logs simply had no severity.",
        "  stage.regex {",
        "    expression = `(?P<f5_msgid>[0-9a-fA-F]{8}):(?P<f5_sev>[0-7]): `",
        "  }",
        "",
        "  // The observer container writes pipe-delimited pairs instead:",
        '  //   "ts"="..."|"l"="info"|"m"="plugin loaded"|...',
        "  // Backtick raw strings throughout: these patterns are full of",
        "  // quotes, and escaping them through two layers loses backslashes",
        "  // quietly rather than loudly.",
        "  stage.regex {",
        '    expression = `"l"="(?P<obs_level>[a-z]+)"`',
        "  }",
        "",
        "  // Severity as a queryable label. F5 uses numeric syslog",
        "  // severities, which are inverted (0 is worst) — not something to",
        "  // make an operator translate at 3am, so they are spelled out.",
        "  stage.template {",
        '    source   = "level"',
        '    template = `{{ if .obs_level }}{{ .obs_level }}{{ else if .f5_sev }}{{ if eq .f5_sev "0" }}emergency{{ else if eq .f5_sev "1" }}alert{{ else if eq .f5_sev "2" }}critical{{ else if eq .f5_sev "3" }}error{{ else if eq .f5_sev "4" }}warning{{ else if eq .f5_sev "5" }}notice{{ else if eq .f5_sev "6" }}info{{ else }}debug{{ end }}{{ else }}unknown{{ end }}`',
        "  }",
        "",
        "  stage.labels {",
        "    values = { level = null }",
        "  }",
        "",
        "  // The message id identifies the *kind* of event and is what you",
        "  // grep for, but it has hundreds of values — structured metadata,",
        "  // not a label, or every distinct id forks a new stream.",
        "  stage.structured_metadata {",
        "    values = { f5_msgid = null }",
        "  }",
        "}",
        "",
    ]
    return "\n".join(blocks)


def publish(db: Session) -> dict[str, Any]:
    """Write the kubeconfigs and Alloy config, and reload Alloy if it changed."""
    TELEMETRY_DIR.mkdir(parents=True, exist_ok=True)
    clusters = publish_kubeconfigs(db)
    rendered = render_alloy_config(clusters)

    previous = ALLOY_CONFIG.read_text() if ALLOY_CONFIG.exists() else None
    if previous == rendered:
        return {"clusters": len(clusters), "changed": False, "reloaded": False}

    ALLOY_CONFIG.write_text(rendered)
    logger.info("Wrote collector config for %d cluster(s)", len(clusters))
    return {
        "clusters": len(clusters),
        "changed": True,
        "reloaded": reload_alloy(),
    }


def reload_alloy() -> bool:
    """Ask Alloy to re-read its config. False when it is not running yet."""
    try:
        resp = requests.post(ALLOY_RELOAD_URL, timeout=5)
        resp.raise_for_status()
        return True
    except requests.RequestException as exc:
        # Normal at first start: the backend writes the config before Alloy
        # exists. Alloy reads it on boot, so nothing is lost.
        logger.debug("Alloy reload skipped: %s", exc)
        return False
