"""Canonical MCP tool catalog for MCP governance/productization.

Slice 11 compatibility/deprecation policy (lightweight, enforced):
- Full coverage for governed modules:
  system, cluster_management, helm, config_management, iac_operations, bnk_operations
- Lifecycle metadata is mandatory on every entry:
  `stability`, `since_version`, `deprecated`, `replacement_tool`
- Deprecated tools remain callable during a documented compatibility window;
  removal must be an explicit follow-up change (never silent).
- If `replacement_tool` is set, it must reference a real, different tool.

The catalog is intentionally not full-server coverage yet. Tests enforce that covered
modules stay fully cataloged and that all catalog entries stay URL-audit aligned.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from enum import Enum


class ToolRiskClass(str, Enum):
    """Simple risk classes for MCP productization/safety workflows."""

    READ_ONLY = "read_only"
    MUTATING = "mutating"
    DESTRUCTIVE = "destructive"


class ToolAuthExpectation(str, Enum):
    """Allowed auth expectation vocabulary for catalog governance."""

    VIEWER = "viewer"
    OPERATOR = "operator"
    ADMIN = "admin"
    CLUSTER_OWNER = "cluster_owner"
    MODULE_OWNER = "module_owner"
    PROJECT_OWNER = "project_owner"
    AUTHENTICATED = "authenticated"


class ToolStability(str, Enum):
    """Lightweight lifecycle stability markers for MCP consumers."""

    EXPERIMENTAL = "experimental"
    STABLE = "stable"
    INTERNAL = "internal"


@dataclass(frozen=True)
class ToolCatalogEntry:
    """Single MCP tool catalog entry."""

    tool_name: str
    module: str
    http_method: str
    backend_path_template: str
    auth_expectation: str
    risk_class: ToolRiskClass
    uses_query_params: bool
    uses_json_body: bool
    tier: str
    stability: ToolStability
    since_version: str
    deprecated: bool
    replacement_tool: str | None
    notes: str


HIGH_RISK_TOOL_CATALOG: tuple[ToolCatalogEntry, ...] = (
    # ------------------------------------------------------------------
    # System (full module coverage in governed scope)
    # ------------------------------------------------------------------
    ToolCatalogEntry(
        tool_name="system_health",
        module="system",
        http_method="GET",
        backend_path_template="/api/system/health",
        auth_expectation="admin",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Admin-only system health route under /api/system router-level auth dependency.",
    ),
    ToolCatalogEntry(
        tool_name="system_version",
        module="system",
        http_method="GET",
        backend_path_template="/api/version",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Version endpoint protected by viewer role.",
    ),
    ToolCatalogEntry(
        tool_name="system_settings",
        module="system",
        http_method="GET",
        backend_path_template="/api/settings",
        auth_expectation="admin",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Admin-only settings view.",
    ),
    ToolCatalogEntry(
        tool_name="list_users",
        module="system",
        http_method="GET",
        backend_path_template="/api/auth/users",
        auth_expectation="admin",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Admin-only auth user inventory.",
    ),
    ToolCatalogEntry(
        tool_name="system_queue_metrics",
        module="system",
        http_method="GET",
        backend_path_template="/api/system/queue-metrics",
        auth_expectation="admin",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Admin-only Celery/worker queue depth.",
    ),
    ToolCatalogEntry(
        tool_name="audit_log",
        module="system",
        http_method="GET",
        backend_path_template="/api/audit",
        auth_expectation="authenticated",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="MCP maps limit→page_size query param; non-admin sees own logs.",
    ),
    # ------------------------------------------------------------------
    # Cluster management (full module coverage in governed scope)
    # ------------------------------------------------------------------
    ToolCatalogEntry(
        tool_name="list_clusters",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Global cluster inventory endpoint.",
    ),
    ToolCatalogEntry(
        tool_name="create_cluster",
        module="cluster_management",
        http_method="POST",
        backend_path_template="/api/projects/{project_id}/k8s/clusters",
        auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="3.1",
        deprecated=False,
        replacement_tool=None,
        notes="Register a cluster under a project via ClusterCreateRequest body; primary entry point for external provisioners (e.g. awsbnkctl).",
    ),
    ToolCatalogEntry(
        tool_name="detect_eks_clusters",
        module="cluster_management",
        http_method="POST",
        backend_path_template="/api/projects/{project_id}/k8s/clusters/detect-eks",
        auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="3.1",
        deprecated=False,
        replacement_tool=None,
        notes="Auto-discover and register EKS clusters from a project's IaC modules; idempotent (re-runs surface existing rows).",
    ),
    ToolCatalogEntry(
        tool_name="get_cluster",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Cluster detail payload.",
    ),
    ToolCatalogEntry(
        tool_name="test_cluster_connectivity",
        module="cluster_management",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/test",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Connectivity probe POST with no body.",
    ),
    ToolCatalogEntry(
        tool_name="scan_cluster",
        module="cluster_management",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/scan",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Cluster scanner trigger; route currently accepts empty body.",
    ),
    ToolCatalogEntry(
        tool_name="list_namespaces",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/namespaces",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Namespace list wrapper over KubernetesService.list_namespaces.",
    ),
    ToolCatalogEntry(
        tool_name="list_resources",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Optional namespace query param only when provided.",
    ),
    ToolCatalogEntry(
        tool_name="get_resource",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}/{name}/describe",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=True,
        replacement_tool="describe_resource",
        notes=(
            "Deprecated alias of describe_resource; kept callable for compatibility. "
            "Use describe_resource for new consumers. Planned removal no earlier than v2.12."
        ),
    ),
    ToolCatalogEntry(
        tool_name="get_pod_logs",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/pods/{pod_name}/logs",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace required; container/tail_lines optional query params.",
    ),
    ToolCatalogEntry(
        tool_name="describe_resource",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}/{name}/describe",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Same backend route as get_resource; richer describe semantics.",
    ),
    ToolCatalogEntry(
        tool_name="get_cluster_events",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/events",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="MCP sends limit and optional namespace query params.",
    ),
    ToolCatalogEntry(
        tool_name="get_node_metrics",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/top/nodes",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Node top metrics.",
    ),
    ToolCatalogEntry(
        tool_name="get_pod_metrics",
        module="cluster_management",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/top/pods",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Optional namespace query param.",
    ),
    # Platform mutation/recovery
    ToolCatalogEntry(
        tool_name="restart_pod",
        module="cluster_management",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/pods/{pod_name}/restart",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace required as query param by backend signature.",
    ),
    ToolCatalogEntry(
        tool_name="scale_deployment",
        module="cluster_management",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/deployments/{name}/scale",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace + replicas in JSON body (ScaleDeploymentRequest).",
    ),
    # Cluster CRUD (extended)
    ToolCatalogEntry(
        tool_name="update_cluster", module="cluster_management", http_method="PUT",
        backend_path_template="/api/k8s/clusters/{cluster_id}", auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Update mutable cluster fields (kubeconfig swap for EKS token rotation, rename, prereqs).",
    ),
    ToolCatalogEntry(
        tool_name="delete_cluster", module="cluster_management", http_method="DELETE",
        backend_path_template="/api/k8s/clusters/{cluster_id}", auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.DESTRUCTIVE, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Removes forge's cluster registration only; does not destroy underlying cluster.",
    ),
    ToolCatalogEntry(
        tool_name="refresh_kubeconfig", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/refresh-kubeconfig",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="EKS: aws eks update-kubeconfig; on-prem: re-probe SSH endpoint.",
    ),
    # Resource lifecycle (apply/update/patch/delete/label/annotate)
    ToolCatalogEntry(
        tool_name="apply_resource", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl apply equivalent; ResourceCreateRequest body (resource_yaml + namespace + dry_run).",
    ),
    ToolCatalogEntry(
        tool_name="update_resource", module="cluster_management", http_method="PUT",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}/{resource_name}",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl replace equivalent; full YAML replacement.",
    ),
    ToolCatalogEntry(
        tool_name="patch_resource", module="cluster_management", http_method="PATCH",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}/{resource_name}",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl patch equivalent; ResourcePatchRequest body with strategic/merge/json patch type.",
    ),
    ToolCatalogEntry(
        tool_name="delete_resource", module="cluster_management", http_method="DELETE",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}/{resource_name}",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl delete equivalent; namespace + dry_run as query params.",
    ),
    ToolCatalogEntry(
        tool_name="label_resource", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}/{resource_name}/label",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl label equivalent; LabelResourceRequest body.",
    ),
    ToolCatalogEntry(
        tool_name="annotate_resource", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/resources/{resource_type}/{resource_name}/annotate",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl annotate equivalent; AnnotateResourceRequest body.",
    ),
    # Deployment rollouts
    ToolCatalogEntry(
        tool_name="rollout_history", module="cluster_management", http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/deployments/{deployment_name}/rollout/history",
        auth_expectation="viewer", risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl rollout history equivalent; namespace required query param.",
    ),
    ToolCatalogEntry(
        tool_name="rollout_status", module="cluster_management", http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/deployments/{deployment_name}/rollout/status",
        auth_expectation="viewer", risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl rollout status equivalent.",
    ),
    ToolCatalogEntry(
        tool_name="rollout_undo", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/deployments/{deployment_name}/rollout/undo",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Rolls deployment back; namespace + optional to_revision query params.",
    ),
    ToolCatalogEntry(
        tool_name="rollout_restart", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/deployments/{deployment_name}/rollout/restart",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Forces rolling pod recreation; common after ConfigMap/Secret update.",
    ),
    ToolCatalogEntry(
        tool_name="rollout_pause", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/deployments/{deployment_name}/rollout/pause",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Pauses in-flight rollout.",
    ),
    ToolCatalogEntry(
        tool_name="rollout_resume", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/deployments/{deployment_name}/rollout/resume",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Resumes paused rollout.",
    ),
    # Node ops
    ToolCatalogEntry(
        tool_name="cordon_node", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/nodes/{node_name}/cordon",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl cordon equivalent; marks node unschedulable.",
    ),
    ToolCatalogEntry(
        tool_name="uncordon_node", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/nodes/{node_name}/uncordon",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl uncordon equivalent.",
    ),
    ToolCatalogEntry(
        tool_name="drain_node", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/nodes/{node_name}/drain",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="kubectl drain equivalent; ignore_daemonsets + delete_emptydir_data query params.",
    ),
    # Tunnels
    ToolCatalogEntry(
        tool_name="open_tunnel", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/tunnel/open",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Pre-open SSH tunnel for on-prem clusters; on-demand otherwise.",
    ),
    ToolCatalogEntry(
        tool_name="close_tunnel", module="cluster_management", http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/tunnel/close",
        auth_expectation="cluster_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Drop SSH tunnel without restarting backend.",
    ),
    # ------------------------------------------------------------------
    # Helm (full module coverage in governed scope)
    # ------------------------------------------------------------------
    ToolCatalogEntry(
        tool_name="helm_list_repos",
        module="helm",
        http_method="GET",
        backend_path_template="/api/helm/repositories",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Global Helm repository listing.",
    ),
    ToolCatalogEntry(
        tool_name="helm_add_repo",
        module="helm",
        http_method="POST",
        backend_path_template="/api/helm/repositories",
        auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Adds global repository metadata.",
    ),
    ToolCatalogEntry(
        tool_name="helm_search_charts",
        module="helm",
        http_method="GET",
        backend_path_template="/api/helm/charts/search",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="keyword query param optional in MCP wrapper.",
    ),
    ToolCatalogEntry(
        tool_name="helm_list_releases",
        module="helm",
        http_method="GET",
        backend_path_template="/api/k8s/{cluster_id}/helm/releases",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Optional namespace query filter.",
    ),
    ToolCatalogEntry(
        tool_name="helm_get_release",
        module="helm",
        http_method="GET",
        backend_path_template="/api/k8s/{cluster_id}/helm/releases/{release_name}",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace query param required by backend handler.",
    ),
    ToolCatalogEntry(
        tool_name="helm_get_values",
        module="helm",
        http_method="GET",
        backend_path_template="/api/k8s/{cluster_id}/helm/releases/{release_name}/values",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace query param required by backend handler.",
    ),
    ToolCatalogEntry(
        tool_name="helm_release_history",
        module="helm",
        http_method="GET",
        backend_path_template="/api/k8s/{cluster_id}/helm/releases/{release_name}/history",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace query param required by backend handler.",
    ),
    # Helm mutating
    ToolCatalogEntry(
        tool_name="helm_install",
        module="helm",
        http_method="POST",
        backend_path_template="/api/k8s/{cluster_id}/helm/install",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Namespace must be in request body via InstallChartRequest.",
    ),
    ToolCatalogEntry(
        tool_name="helm_upgrade",
        module="helm",
        http_method="PUT",
        backend_path_template="/api/k8s/{cluster_id}/helm/releases/{release_name}/upgrade",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=True,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace is query param; body excludes namespace (UpgradeReleaseRequest).",
    ),
    ToolCatalogEntry(
        tool_name="helm_rollback",
        module="helm",
        http_method="POST",
        backend_path_template="/api/k8s/{cluster_id}/helm/releases/{release_name}/rollback",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=True,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace query param; revision in body.",
    ),
    ToolCatalogEntry(
        tool_name="helm_uninstall",
        module="helm",
        http_method="DELETE",
        backend_path_template="/api/k8s/{cluster_id}/helm/releases/{release_name}",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="namespace query param; release deletion is high blast radius.",
    ),
    # ------------------------------------------------------------------
    # Config management (full module coverage in governed scope)
    # ------------------------------------------------------------------
    ToolCatalogEntry(
        tool_name="config_export",
        module="config_management",
        http_method="GET",
        backend_path_template="/api/clusters/{cluster_id}/bnk/export",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Default export path returns YAML; MCP chooses /json variant when format='json'.",
    ),
    ToolCatalogEntry(
        tool_name="config_diff",
        module="config_management",
        http_method="POST",
        backend_path_template="/api/clusters/bnk/diff",
        auth_expectation="operator",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Comparison endpoint computes differences without mutating cluster state.",
    ),
    ToolCatalogEntry(
        tool_name="config_import",
        module="config_management",
        http_method="POST",
        backend_path_template="/api/clusters/{cluster_id}/bnk/import",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Backend expects ConfigImportRequest with top-level 'config' object.",
    ),
    ToolCatalogEntry(
        tool_name="config_promote",
        module="config_management",
        http_method="POST",
        backend_path_template="/api/config/promote",
        auth_expectation="operator",
        risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="dry_run=False applies cross-cluster changes; deletions intentionally skipped by backend.",
    ),
    # ------------------------------------------------------------------
    # BNK operations (full module coverage in governed scope)
    # ------------------------------------------------------------------
    ToolCatalogEntry(
        tool_name="bnk_data",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/f5bnk/data",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Unified BNK data endpoint with optional namespace query filter.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_gateway_topology",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/f5bnk/gateway-topology",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="GatewayClass→Gateway→HTTPRoute→backend topology view.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_health",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/f5bnk/health",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="BNK health analysis derived from unified data fetch.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_policy_associations",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/f5bnk/policy-gateway-associations",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Policy attachment graph for gateways/routes.",
    ),
    ToolCatalogEntry(
        tool_name="a2a_discover_agents",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/f5bnk/a2a/agents",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Optional probe=true query triggers backend service probing for agent cards.",
    ),
    ToolCatalogEntry(
        tool_name="tmm_list_pods",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/tmm-debug/pods",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="List TMM pods and debug-container availability.",
    ),
    ToolCatalogEntry(
        tool_name="tmm_exec_command",
        module="bnk_operations",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/tmm-debug/exec",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Arbitrary debug-sidecar command execution endpoint; auth is viewer but blast radius exceeds pure read.",
    ),
    ToolCatalogEntry(
        tool_name="tmm_configview",
        module="bnk_operations",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/tmm-debug/configview",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Structured configview inspection by pod/namespace.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_current_version",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/bnk/upgrade/current",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Current BNK/FLO version detection endpoint.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_available_versions",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/bnk/upgrade/versions",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Available upgrade targets with registry availability metadata.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_upgrade_plan",
        module="bnk_operations",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/bnk/upgrade/plan",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Creates persisted upgrade plan state after pre-checks.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_upgrade_execute",
        module="bnk_operations",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/bnk/upgrade/{upgrade_id}/execute",
        auth_expectation="cluster_owner",
        risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Starts asynchronous in-cluster upgrade execution workflow.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_upgrade_history",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/bnk/upgrade/history",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Supports limit query parameter.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_license_status",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/licensing/{cluster_id}/status",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="License and telemetry status endpoint.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_telemetry_report",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/licensing/{cluster_id}/report",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Fetch licensing telemetry manifest/report payload.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_recovery_cert_sync",
        module="bnk_operations",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/recovery/cwc-certs",
        auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="No body/query expected; endpoint runs cert sync workflow.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_platform_restart",
        module="bnk_operations",
        http_method="POST",
        backend_path_template="/api/k8s/clusters/{cluster_id}/recovery/platform-restart",
        auth_expectation="operator",
        risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Backend expects PlatformRestartRequest body; MCP sends defaults.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_license_renew",
        module="bnk_operations",
        http_method="POST",
        backend_path_template="/api/licensing/{cluster_id}/renew",
        auth_expectation="operator",
        risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="JWT in JSON body; renewal includes CWC restart and state reset.",
    ),
    ToolCatalogEntry(
        tool_name="bnk_recovery_status",
        module="bnk_operations",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/recovery/status",
        auth_expectation="operator",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Recovery preflight checks are operator-gated under recovery router.",
    ),
    # ------------------------------------------------------------------
    # IaC operations (full module coverage in governed scope)
    # ------------------------------------------------------------------
    ToolCatalogEntry(
        tool_name="list_projects",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/projects",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Project inventory route.",
    ),
    ToolCatalogEntry(
        tool_name="get_project",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/projects/{project_id}",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Project detail endpoint.",
    ),
    ToolCatalogEntry(
        tool_name="create_project",
        module="iac_operations",
        http_method="POST",
        backend_path_template="/api/projects",
        auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="3.1",
        deprecated=False,
        replacement_tool=None,
        notes="Create a project via ProjectCreate body; calling user becomes owner. Required for MCP-only deployment registration flows (eliminates need for REST fallback when bootstrapping a project from external tools).",
    ),
    ToolCatalogEntry(
        tool_name="update_project", module="iac_operations", http_method="PUT",
        backend_path_template="/api/projects/{project_id}", auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Update mutable project fields via ProjectUpdate body.",
    ),
    ToolCatalogEntry(
        tool_name="delete_project", module="iac_operations", http_method="DELETE",
        backend_path_template="/api/projects/{project_id}", auth_expectation="project_owner",
        risk_class=ToolRiskClass.DESTRUCTIVE, uses_query_params=True, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Delete project; force query param bypasses active/only-project safety check.",
    ),
    ToolCatalogEntry(
        tool_name="activate_project", module="iac_operations", http_method="POST",
        backend_path_template="/api/projects/{project_id}/activate", auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Sets project as active; UI surfaces active project prominently.",
    ),
    ToolCatalogEntry(
        tool_name="project_dependency_graph",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/project-modules/project/{project_id}/dependency-graph",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Dependency DAG for module orchestration order.",
    ),
    ToolCatalogEntry(
        tool_name="list_project_modules",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/project-modules/project/{project_id}",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="List modules configured in a project.",
    ),
    ToolCatalogEntry(
        tool_name="create_project_module",
        module="iac_operations",
        http_method="POST",
        backend_path_template="/api/project-modules/project/{project_id}/add",
        auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="3.1",
        deprecated=False,
        replacement_tool=None,
        notes="Add a module from the library to a project via AddModuleRequest body. path_in_project is validated against `^[a-zA-Z0-9/_-]+$`; variable names against snake_case; values against shell-metachar denylist.",
    ),
    ToolCatalogEntry(
        tool_name="update_project_module", module="iac_operations", http_method="PUT",
        backend_path_template="/api/project-modules/{module_id}", auth_expectation="module_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Update variable_overrides / deployment_order / enabled (UpdateModuleRequest body).",
    ),
    ToolCatalogEntry(
        tool_name="change_project_module_version", module="iac_operations", http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/change-version", auth_expectation="module_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.2",
        deprecated=False, replacement_tool=None,
        notes="D-033: re-pin a project module to another immutable catalog version of its path (ChangeModuleVersionRequest body). Takes effect on the module's next plan/apply/destroy.",
    ),
    ToolCatalogEntry(
        tool_name="delete_project_module", module="iac_operations", http_method="DELETE",
        backend_path_template="/api/project-modules/{module_id}", auth_expectation="module_owner",
        risk_class=ToolRiskClass.DESTRUCTIVE, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Removes module from project; does not run terraform destroy first (caller's responsibility).",
    ),
    # Module execution (init/deploy/cancel/retry; plan/apply/destroy elsewhere)
    ToolCatalogEntry(
        tool_name="project_module_init", module="iac_operations", http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/init", auth_expectation="module_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="terraform init — missing first step for newly-added modules; idempotent.",
    ),
    ToolCatalogEntry(
        tool_name="project_module_deploy", module="iac_operations", http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/deploy", auth_expectation="module_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="One-shot init+plan+apply convenience verb; returns task_id.",
    ),
    ToolCatalogEntry(
        tool_name="project_module_cancel", module="iac_operations", http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/cancel", auth_expectation="module_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Cooperative cancel of in-progress plan/apply/destroy.",
    ),
    ToolCatalogEntry(
        tool_name="project_module_retry", module="iac_operations", http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/retry", auth_expectation="module_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Retry the most recent failed apply/destroy with the same parameters.",
    ),
    # Module diagnostics
    ToolCatalogEntry(
        tool_name="get_module_logs", module="iac_operations", http_method="GET",
        backend_path_template="/api/project-modules/{module_id}/logs", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Terraform stdout/stderr for the most recent operation; essential for debugging async runs.",
    ),
    ToolCatalogEntry(
        tool_name="get_module_state_info", module="iac_operations", http_method="GET",
        backend_path_template="/api/project-modules/{module_id}/state-info", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Summary metadata about module's TF state (resource count, version, backend).",
    ),
    ToolCatalogEntry(
        tool_name="recover_module_state", module="iac_operations", http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/recover-state",
        auth_expectation="module_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Unlock stale locks, repair workspace dir — recovery routine for stuck modules.",
    ),
    ToolCatalogEntry(
        tool_name="list_module_catalog",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/module-library",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Module catalog supports optional query filters (category/provider/official/tested).",
    ),
    ToolCatalogEntry(
        tool_name="get_module_state_history",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/project-modules/{module_id}/state-history",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="2.11",
        deprecated=False,
        replacement_tool=None,
        notes="Phase 2 state-machine audit log; use to diagnose stuck deploys.",
    ),
    ToolCatalogEntry(
        tool_name="project_plan",
        module="iac_operations",
        http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/plan",
        auth_expectation="module_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Queues asynchronous OpenTofu plan operation.",
    ),
    ToolCatalogEntry(
        tool_name="project_apply",
        module="iac_operations",
        http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/apply",
        auth_expectation="module_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Backend requires OpenTofuActionRequest body (auto_approve field).",
    ),
    ToolCatalogEntry(
        tool_name="project_destroy",
        module="iac_operations",
        http_method="POST",
        backend_path_template="/api/project-modules/{module_id}/destroy",
        auth_expectation="module_owner",
        risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Backend requires OpenTofuActionRequest body (auto_approve field).",
    ),
    ToolCatalogEntry(
        tool_name="project_deploy_all",
        module="iac_operations",
        http_method="POST",
        backend_path_template="/api/projects/{project_id}/deploy-all",
        auth_expectation="project_owner",
        risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Backend expects DeployAllRequest body with parallel flag.",
    ),
    ToolCatalogEntry(
        tool_name="project_destroy_all",
        module="iac_operations",
        http_method="POST",
        backend_path_template="/api/projects/{project_id}/destroy-all",
        auth_expectation="project_owner",
        risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Backend expects DestroyAllRequest body with parallel flag.",
    ),
    ToolCatalogEntry(
        tool_name="deployment_history",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/project-modules/project/{project_id}/deployments",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Project-level deployment timeline with optional filtering and limit params.",
    ),
    ToolCatalogEntry(
        tool_name="list_stacks",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/stacks/templates",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Stack template inventory supports optional category/provider/tag filters.",
    ),
    ToolCatalogEntry(
        tool_name="get_stack",
        module="iac_operations",
        http_method="GET",
        backend_path_template="/api/stacks/templates/{slug}",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Stack template detail by slug.",
    ),
    ToolCatalogEntry(
        tool_name="deploy_stack",
        module="iac_operations",
        http_method="POST",
        backend_path_template="/api/stacks/projects/{project_id}/stacks/{stack_id}/deploy",
        auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Path-only invocation; starts stack deployment workflow.",
    ),
    # Stack template introspection + instance lifecycle
    ToolCatalogEntry(
        tool_name="stack_template_preview", module="iac_operations", http_method="GET",
        backend_path_template="/api/stacks/templates/{slug}/preview", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Preview the modules a stack template would instantiate.",
    ),
    ToolCatalogEntry(
        tool_name="stack_template_required_inputs", module="iac_operations", http_method="GET",
        backend_path_template="/api/stacks/templates/{slug}/required-inputs", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Per-variable metadata (name, type, description, default).",
    ),
    ToolCatalogEntry(
        tool_name="stack_template_check_prerequisites", module="iac_operations", http_method="GET",
        backend_path_template="/api/stacks/templates/{slug}/check-prerequisites",
        auth_expectation="viewer", risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Per-prereq pass/fail (cluster exists, AWS creds configured, etc.).",
    ),
    ToolCatalogEntry(
        tool_name="create_stack_instance", module="iac_operations", http_method="POST",
        backend_path_template="/api/stacks/projects/{project_id}/stacks", auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Missing first step before deploy_stack; StackInstanceCreate body (template_id + name + variables).",
    ),
    ToolCatalogEntry(
        tool_name="get_stack_instance", module="iac_operations", http_method="GET",
        backend_path_template="/api/stacks/projects/{project_id}/stacks/{stack_id}",
        auth_expectation="viewer", risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Stack instance detail incl. deployed modules.",
    ),
    ToolCatalogEntry(
        tool_name="stack_instance_status", module="iac_operations", http_method="GET",
        backend_path_template="/api/stacks/projects/{project_id}/stacks/{stack_id}/status",
        auth_expectation="viewer", risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Rollout status: current_step, total_steps, error_message, timestamps.",
    ),
    ToolCatalogEntry(
        tool_name="delete_stack_instance", module="iac_operations", http_method="DELETE",
        backend_path_template="/api/stacks/projects/{project_id}/stacks/{stack_id}",
        auth_expectation="project_owner", risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Removes stack record; does not run terraform destroy on member modules.",
    ),
    # Task tracking (apply/destroy/deploy return task_ids — these track them)
    ToolCatalogEntry(
        tool_name="get_task", module="iac_operations", http_method="GET",
        backend_path_template="/api/tasks/{task_id}", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Poll any async operation's task_id (apply, destroy, deploy, upgrade).",
    ),
    ToolCatalogEntry(
        tool_name="cancel_task", module="iac_operations", http_method="POST",
        backend_path_template="/api/tasks/{task_id}/cancel", auth_expectation="viewer",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Cooperative cancel; backend tasks router uses require_viewer at the router level.",
    ),
    # Project secrets
    ToolCatalogEntry(
        tool_name="list_project_secrets", module="iac_operations", http_method="GET",
        backend_path_template="/api/projects/{project_id}/secrets", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Metadata only — never returns secret material.",
    ),
    ToolCatalogEntry(
        tool_name="create_project_secret_value", module="iac_operations", http_method="POST",
        backend_path_template="/api/projects/{project_id}/secrets/value",
        auth_expectation="project_owner", risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Encrypted at rest; injected as TF var at deploy time when target_variable_name set.",
    ),
    ToolCatalogEntry(
        tool_name="delete_project_secret", module="iac_operations", http_method="DELETE",
        backend_path_template="/api/projects/{project_id}/secrets/{secret_id}",
        auth_expectation="project_owner", risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Module runs that depend on this secret will fail until recreated.",
    ),
    ToolCatalogEntry(
        tool_name="list_required_project_secrets", module="iac_operations", http_method="GET",
        backend_path_template="/api/projects/{project_id}/secrets/required", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Canonical required set from module declarations + well-known secrets (cne_pull_secret, jwt_token).",
    ),
    # ------------------------------------------------------------------
    # Cloud authentication (new governed module in 3.1)
    # ------------------------------------------------------------------
    ToolCatalogEntry(
        tool_name="list_aws_regions", module="cloud_auth", http_method="GET",
        backend_path_template="/api/cloud-auth/aws/regions", auth_expectation="operator",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Validated AWS regions list (router-level require_operator dep).",
    ),
    ToolCatalogEntry(
        tool_name="aws_sso_initiate", module="cloud_auth", http_method="POST",
        backend_path_template="/api/cloud-auth/aws/sso/initiate", auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="AWS IAM Identity Center device authorization start.",
    ),
    ToolCatalogEntry(
        tool_name="aws_sso_poll", module="cloud_auth", http_method="POST",
        backend_path_template="/api/cloud-auth/aws/sso/poll", auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Poll SSO device auth for access token; retry on authorization_pending.",
    ),
    ToolCatalogEntry(
        tool_name="aws_set_project_credentials", module="cloud_auth", http_method="POST",
        backend_path_template="/api/cloud-auth/aws/credentials", auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Exchange SSO access token for account+role STS creds; stores under project_id.",
    ),
    ToolCatalogEntry(
        tool_name="aws_assume_role", module="cloud_auth", http_method="POST",
        backend_path_template="/api/cloud-auth/aws/assume-role", auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="STS AssumeRole using project creds; refreshes short-lived pair.",
    ),
    ToolCatalogEntry(
        tool_name="get_project_aws_credentials", module="cloud_auth", http_method="GET",
        backend_path_template="/api/cloud-auth/aws/credentials/{project_id}",
        auth_expectation="operator", risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Metadata only — never returns secret access key.",
    ),
    ToolCatalogEntry(
        tool_name="delete_project_aws_credentials", module="cloud_auth", http_method="DELETE",
        backend_path_template="/api/cloud-auth/aws/credentials/{project_id}",
        auth_expectation="operator", risk_class=ToolRiskClass.DESTRUCTIVE,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Removes stored project credential record; does not revoke underlying IAM role.",
    ),
    ToolCatalogEntry(
        tool_name="list_credential_templates", module="cloud_auth", http_method="GET",
        backend_path_template="/api/credential-templates", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Reusable credential bundles (AWS/Azure/GCP/IBM/SSH).",
    ),
    ToolCatalogEntry(
        tool_name="create_credential_template", module="cloud_auth", http_method="POST",
        backend_path_template="/api/credential-templates", auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="CredentialTemplateCreate body; provider-specific fields ignored when irrelevant.",
    ),
    ToolCatalogEntry(
        tool_name="test_credential_template", module="cloud_auth", http_method="POST",
        backend_path_template="/api/credential-templates/{template_id}/test",
        auth_expectation="operator", risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Provider-side validation (STS GetCallerIdentity, IBM IAM ping, SSH probe).",
    ),
    ToolCatalogEntry(
        tool_name="list_ssh_credentials", module="cloud_auth", http_method="GET",
        backend_path_template="/api/ssh-credentials", auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY, uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Metadata only — never returns private key/password.",
    ),
    ToolCatalogEntry(
        tool_name="create_ssh_credential", module="cloud_auth", http_method="POST",
        backend_path_template="/api/ssh-credentials", auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING, uses_query_params=False, uses_json_body=True,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Encrypted at rest; auth_type pattern '^(password|key)$'.",
    ),
    ToolCatalogEntry(
        tool_name="test_ssh_credential", module="cloud_auth", http_method="POST",
        backend_path_template="/api/ssh-credentials/{credential_id}/test",
        auth_expectation="operator", risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False, uses_json_body=False,
        tier="tier1", stability=ToolStability.STABLE, since_version="3.1",
        deprecated=False, replacement_tool=None,
        notes="Opens test SSH connection; does not execute commands.",
    ),
    # ------------------------------------------------------------------
    # Diagnostics & Fleet (full module coverage in governed scope)
    # ------------------------------------------------------------------
    ToolCatalogEntry(
        tool_name="qkview_create",
        module="diagnostics_fleet",
        http_method="POST",
        backend_path_template="/api/qkview/create",
        auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Creates a QKView diagnostic tarball; async operation (require_operator).",
    ),
    ToolCatalogEntry(
        tool_name="qkview_list",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/qkview/list",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Lists available QKView files for a cluster (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="qkview_status",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/qkview/{qkview_id}/status",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Polls QKView job status (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="qkview_setup_certs",
        module="diagnostics_fleet",
        http_method="POST",
        backend_path_template="/api/licensing/{cluster_id}/cwc-setup",
        auth_expectation="operator",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Sets up shared CWC mTLS certs via cert-manager (require_operator).",
    ),
    ToolCatalogEntry(
        tool_name="fleet_health",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/operators/fleet-health",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Aggregate fleet health across all operators (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="list_operators",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/operators",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Lists all registered operators and their status (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="drift_check",
        module="diagnostics_fleet",
        http_method="POST",
        backend_path_template="/api/projects/{project_id}/drift/check-now",
        auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Triggers a drift check for a project (require_project_owner).",
    ),
    ToolCatalogEntry(
        tool_name="drift_history",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/projects/{project_id}/drift/checks",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=True,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Drift detection history for a project (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="list_snapshots",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/projects/{project_id}/snapshots",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Lists config snapshots for a project (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="create_snapshot",
        module="diagnostics_fleet",
        http_method="POST",
        backend_path_template="/api/projects/{project_id}/snapshots",
        auth_expectation="project_owner",
        risk_class=ToolRiskClass.MUTATING,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Creates a config snapshot of a project's current state (require_project_owner).",
    ),
    ToolCatalogEntry(
        tool_name="compare_snapshots",
        module="diagnostics_fleet",
        http_method="POST",
        backend_path_template="/api/snapshots/diff",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Compares two snapshots; read-only POST (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="list_runbooks",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/runbooks",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Lists available diagnostic runbooks (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="execute_runbook",
        module="diagnostics_fleet",
        http_method="POST",
        backend_path_template="/api/runbooks/{runbook_id}/run",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=True,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Executes a diagnostic runbook (read-only diagnostics, require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="cluster_connectivity",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/connectivity",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Probes connectivity to a single cluster (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="cluster_connectivity_batch",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/connectivity",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Probes connectivity to all clusters in parallel (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="dpf_detect",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/dpf/detect",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Detects DPF CRDs on a cluster (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="dpf_data",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/dpf/data",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Gets DPF data including DPU devices and services (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="dpf_health",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/k8s/clusters/{cluster_id}/dpf/health",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Gets DPF health status for a cluster (require_viewer).",
    ),
    ToolCatalogEntry(
        tool_name="list_alert_channels",
        module="diagnostics_fleet",
        http_method="GET",
        backend_path_template="/api/alert-channels",
        auth_expectation="viewer",
        risk_class=ToolRiskClass.READ_ONLY,
        uses_query_params=False,
        uses_json_body=False,
        tier="tier1",
        stability=ToolStability.STABLE,
        since_version="pre-2.10.71",
        deprecated=False,
        replacement_tool=None,
        notes="Lists configured alert channels (require_viewer).",
    ),
)


GOVERNED_MODULES: tuple[str, ...] = (
    "system",
    "cluster_management",
    "helm",
    "config_management",
    "iac_operations",
    "bnk_operations",
    "cloud_auth",
    "diagnostics_fleet",
)


# Keep this explicit and stable for docs/tests/CI policy checks.
ALLOWED_AUTH_EXPECTATIONS: tuple[str, ...] = tuple(expectation.value for expectation in ToolAuthExpectation)
ALLOWED_TOOL_STABILITY: tuple[str, ...] = tuple(stability.value for stability in ToolStability)


def get_high_risk_tool_catalog() -> list[dict[str, object]]:
    """Return catalog entries as plain dictionaries for JSON serialization/tests."""

    return [asdict(entry) for entry in HIGH_RISK_TOOL_CATALOG]
