/**
 * Convenience re-exports of generated OpenAPI schema types.
 *
 * Usage:
 *   import type { ProjectCreate, SettingsBatchUpdate } from '@/types/api-schemas';
 *
 * These types are auto-generated from the backend Pydantic schemas via:
 *   1. `make openapi`       — generates backend/openapi.json from FastAPI
 *   2. `make openapi-types` — generates src/types/api-generated.ts from the spec
 *
 * If the backend schema changes and the frontend sends the wrong shape,
 * TypeScript will catch it at compile time.
 *
 * DO NOT edit this file to add hand-written types. Add them to the
 * domain-specific files (projects.ts, helm.ts, etc.) instead.
 * Only add re-exports of generated schema types here.
 */
import type { components } from './api-generated';

// Helper type to extract schemas from the generated spec
type Schemas = components['schemas'];

/**
 * Compile-time key contract check.
 *
 * Verifies that every key in FrontendType also exists in BackendType.
 * If the frontend sends a field that the backend schema doesn't have,
 * TypeScript will produce an error at the usage site:
 *
 *   "Type 'false' is not assignable to type 'true'"
 *
 * This is looser than direct type assignment (which fails on undefined/null
 * mismatches). It only checks that the KEY NAMES match — not the exact
 * value types. This is intentional: JSON serialization drops `undefined`,
 * and the backend applies Pydantic defaults, so `undefined` in TS safely
 * maps to a backend default.
 *
 * Usage:
 *   const _check: AssertKeysMatch<ProjectCreateData, ApiProjectCreate> = true;
 *
 * If ProjectCreateData has a key that ApiProjectCreate doesn't, TS errors.
 */
export type AssertKeysMatch<
  FrontendType,
  BackendType,
> = [Exclude<keyof FrontendType, keyof BackendType>] extends [never] ? true : false;

// ── Auth ────────────────────────────────────────────────────────────────────
export type ApiLoginRequest = Schemas['LoginRequest'];
export type ApiChangePasswordRequest = Schemas['ChangePasswordRequest'];
export type ApiUserCreateRequest = Schemas['UserCreateRequest'];
export type ApiUserUpdateRequest = Schemas['UserUpdateRequest'];

// ── Projects ────────────────────────────────────────────────────────────────
// NOTE: target_platform_profile added to backend schema but api-generated.ts not yet regenerated
export type ApiProjectCreate = Schemas['ProjectCreate'] & { target_platform_profile?: string | null };
export type ApiProjectUpdate = Schemas['ProjectUpdate'];
export type ApiTransferOwnershipRequest = Schemas['TransferOwnershipRequest'];
export type ApiVariableDefaultsUpdate = Schemas['VariableDefaultsUpdate'];
export type ApiProjectVariablesUpdate = Schemas['ProjectVariablesUpdate'];
export type ApiDeployAllRequest = Schemas['DeployAllRequest'];
export type ApiDestroyAllRequest = Schemas['DestroyAllRequest'];

// ── Modules ─────────────────────────────────────────────────────────────────
export type ApiAddModuleRequest = Schemas['AddModuleRequest'];
export type ApiUpdateModuleRequest = Schemas['UpdateModuleRequest'];
export type ApiValidateVariablesRequest = Schemas['ValidateVariablesRequest'];
export type ApiSetDependenciesRequest = Schemas['SetDependenciesRequest'];
export type ApiVariableMappingRequest = Schemas['VariableMappingRequest'];
export type ApiVariableMappingTemplateRequest = Schemas['VariableMappingTemplateRequest'];

// ── K8s Clusters ────────────────────────────────────────────────────────────
export type ApiClusterCreateRequest = Schemas['ClusterCreateRequest'];
export type ApiClusterUpdateRequest = Schemas['ClusterUpdateRequest'];
export type ApiConfigImportRequest = Schemas['ConfigImportRequest'];

// ── K8s Resources ───────────────────────────────────────────────────────────
export type ApiResourceCreateRequest = Schemas['ResourceCreateRequest'];
export type ApiResourceUpdateRequest = Schemas['ResourceUpdateRequest'];
export type ApiResourcePatchRequest = Schemas['ResourcePatchRequest'];
export type ApiScaleDeploymentRequest = Schemas['ScaleDeploymentRequest'];
export type ApiLabelResourceRequest = Schemas['LabelResourceRequest'];
export type ApiAnnotateResourceRequest = Schemas['AnnotateResourceRequest'];

// ── K8s Operations ──────────────────────────────────────────────────────────
export type ApiAdaptiveModuleRequest = Schemas['AdaptiveModuleRequest'];

// ── BNK Upgrade ─────────────────────────────────────────────────────────────
export type ApiCreateUpgradePlanRequest = Schemas['CreateUpgradePlanRequest'];

// ── Helm ────────────────────────────────────────────────────────────────────
export type ApiInstallChartRequest = Schemas['InstallChartRequest'];
export type ApiUpgradeReleaseRequest = Schemas['UpgradeReleaseRequest'];
export type ApiRollbackReleaseRequest = Schemas['RollbackReleaseRequest'];
export type ApiAddRepositoryRequest = Schemas['AddRepositoryRequest'];

// ── Operators ───────────────────────────────────────────────────────────────
export type ApiSendCommandRequest = Schemas['SendCommandRequest'];
export type ApiLinkClusterRequest = Schemas['LinkClusterRequest'];
export type ApiSetConnectivityModeRequest = Schemas['SetConnectivityModeRequest'];
export type ApiFanOutCommandRequest = Schemas['FanOutCommandRequest'];

// ── Drift ───────────────────────────────────────────────────────────────────
export type ApiDriftSettingsRequest = Schemas['DriftSettingsRequest'];
export type ApiTriggerDriftCheckRequest = Schemas['TriggerDriftCheckRequest'];

// ── Stacks ──────────────────────────────────────────────────────────────────
export type ApiStackInstanceCreate = Schemas['StackInstanceCreate'];
export type ApiSaveAsTemplateRequest = Schemas['SaveAsTemplateRequest'];
export type ApiDuplicateTemplateRequest = Schemas['DuplicateTemplateRequest'];
export type ApiImportTemplateRequest = Schemas['ImportTemplateRequest'];
export type ApiPublishTemplateRequest = Schemas['PublishTemplateRequest'];

// ── Module Sources ──────────────────────────────────────────────────────────
export type ApiModuleSourceCreate = Schemas['ModuleSourceCreate'];
export type ApiModuleSourceUpdate = Schemas['ModuleSourceUpdate'];

// ── Secrets ─────────────────────────────────────────────────────────────────
export type ApiValueSecretCreate = Schemas['ValueSecretCreate'];
export type ApiValueSecretUpdate = Schemas['ValueSecretUpdate'];

// ── Config Promotion ────────────────────────────────────────────────────────
export type ApiPromoteRequest = Schemas['PromoteRequest'];
export type ApiDiffRequest = Schemas['DiffRequest'];
export type ApiDiffSnapshotsRequest = Schemas['DiffSnapshotsRequest'];

// ── Snapshots ───────────────────────────────────────────────────────────────
export type ApiCreateSnapshotRequest = Schemas['CreateSnapshotRequest'];

// ── System ──────────────────────────────────────────────────────────────────
export type ApiSettingsBatchUpdate = Schemas['SettingsBatchUpdate'];

// ── SSH Credentials ─────────────────────────────────────────────────────────
export type ApiSSHCredentialCreate = Schemas['SSHCredentialCreate'];
export type ApiSSHCredentialUpdate = Schemas['SSHCredentialUpdate'];

// ── Credential Templates ────────────────────────────────────────────────────
export type ApiCredentialTemplateCreate = Schemas['CredentialTemplateCreate'];
export type ApiCredentialTemplateUpdate = Schemas['CredentialTemplateUpdate'];

// ── Alert Channels ──────────────────────────────────────────────────────────
export type ApiAlertChannelCreate = Schemas['AlertChannelCreate'];
export type ApiAlertChannelUpdate = Schemas['AlertChannelUpdate'];

// ── Execution ───────────────────────────────────────────────────────────────
export type ApiOpenTofuActionRequest = Schemas['OpenTofuActionRequest'];

// ── Runbooks ────────────────────────────────────────────────────────────────
export type ApiRunbookExecuteRequest = Schemas['RunbookExecuteRequest'];

// ── Registry ────────────────────────────────────────────────────────────────
export type ApiUserModuleCreate = Schemas['UserModuleCreate'];

// ── Notifications ───────────────────────────────────────────────────────────
export type ApiNotificationCreate = Schemas['NotificationCreate'];
