/**
 * Convenience re-exports of generated OpenAPI schema types.
 *
 * Usage:
 *   import type { ProjectCreate, SettingsBatchUpdate } from '@/types/api-schemas';
 *
 * These types are auto-generated from the backend Pydantic schemas via:
 *   1. `make openapi`       — generates backend/openapi.json from FastAPI
 *   2. `make openapi-types` — generates src/types/api-generated.ts from the spec
 *
 * If the backend schema changes and the frontend sends the wrong shape,
 * TypeScript will catch it at compile time.
 *
 * DO NOT edit this file to add hand-written types. Add them to the
 * domain-specific files (projects.ts, helm.ts, etc.) instead.
 * Only add re-exports of generated schema types here.
 */
import type { components } from './api-generated';

// Helper type to extract schemas from the generated spec
type Schemas = components['schemas'];

/**
 * Compile-time key contract check.
 *
 * Verifies that every key in FrontendType also exists in BackendType.
 * If the frontend sends a field that the backend schema doesn't have,
 * TypeScript will produce an error at the usage site:
 *
 *   "Type 'false' is not assignable to type 'true'"
 *
 * This is looser than direct type assignment (which fails on undefined/null
 * mismatches). It only checks that the KEY NAMES match — not the exact
 * value types. This is intentional: JSON serialization drops `undefined`,
 * and the backend applies Pydantic defaults, so `undefined` in TS safely
 * maps to a backend default.
 *
 * Usage:
 *   const _check: AssertKeysMatch<ProjectCreateData, ApiProjectCreate> = true;
 *
 * If ProjectCreateData has a key that ApiProjectCreate doesn't, TS errors.
 */
export type AssertKeysMatch<
  FrontendType,
  BackendType,
> = [Exclude<keyof FrontendType, keyof BackendType>] extends [never] ? true : false;


// ── K8s Clusters ────────────────────────────────────────────────────────────
export type ApiClusterCreateRequest = Schemas['ClusterCreateRequest'];
export type ApiClusterUpdateRequest = Schemas['ClusterUpdateRequest'];


// ── Operators ───────────────────────────────────────────────────────────────



