"""
SSH module: bare-metal/kubeadm-join

Joins the DPU to the K8s cluster as a worker node using the join command
generated by kubeadm-init.

Runs ON the DPU (target="dpu") via SSH relay through the host.

Implementation note: uses the Python execute() path (overrides execute()) to
guarantee that every step (reset, join, hostname) runs as a discrete SSH call
whose exit code is individually checked.  The shell-streaming path triggered by
estimated_duration loses commands 2-4 when command 1 (kubeadm reset) succeeds,
so the actual join never executes.
"""

import time
from typing import Any

from modules.base import InputSpec, OutputSpec, SSHModule


class KubeadmJoinModule(SSHModule):
    name = "Join DPU to Cluster"
    path = "bare-metal/kubeadm-join"
    category = "bare-metal"
    phase = "DPU Join"
    description = "Join DPU to K8s cluster as worker node"
    version = "1.0.0"

    # SSH config — runs ON the DPU
    target = "dpu"
    estimated_duration = 120
    timeout = 300

    dependencies = ["bare-metal/install-storage"]

    inputs = {
        "bare_metal_host_id": InputSpec(
            name="bare_metal_host_id",
            source="host",
            required=True,
            description="ID of the BareMetalHost",
        ),
        "join_command": InputSpec(
            name="join_command",
            source="module",
            from_module="bare-metal/kubeadm-init",
            from_output="join_command",
            required=True,
            description="kubeadm join command from control plane init",
        ),
        "dpu_vlans": InputSpec(
            name="dpu_vlans",
            source="host",
            required=False,
            default=None,
            description=(
                "List of DPU VLANs (each {name, tag, uplink, ip}) — set by "
                "variable_assembler from bf_conf_renderer. Used to pin the "
                "DPU kubelet's --node-ip to the data-plane VLAN IP "
                "(matches the host's cluster_api_ip subnet) so the K8s "
                "Node InternalIP lands on the VLAN, not on oob_net0."
            ),
        ),
        "rshim_source": InputSpec(
            name="rshim_source",
            source="host",
            required=False,
            default="host",
            description="'host' or 'bmc' — gate the --node-ip pin to dual_dpu_obmc",
        ),
    }

    outputs = {
        "dpu_joined": OutputSpec(
            resource_kind="",
            resource_name="",
            static_value=True,
        ),
        "node_name": OutputSpec(
            resource_kind="",
            resource_name="",
            static_value=None,
        ),
    }

    # ------------------------------------------------------------------
    # Plan — always proceed
    # ------------------------------------------------------------------

    def plan_commands(self, variables: dict[str, Any]) -> list[str]:
        # Check if kubelet is already joined
        return ["sudo systemctl is-active kubelet 2>/dev/null && echo 'ALREADY_JOINED' || echo 'JOIN_NEEDED'"]

    def parse_plan_output(self, output: str, variables: dict[str, Any]) -> bool:
        # If kubelet is active and running, we might already be joined
        # But we should still validate — return True to check
        return True

    # ------------------------------------------------------------------
    # Python execute() path — bypasses apply_commands() / streaming.
    # ------------------------------------------------------------------

    def execute(self, session: Any, variables: dict[str, Any], on_output: Any) -> dict[str, Any]:
        """Join the DPU to the K8s cluster using discrete, exit-code-checked SSH calls.

        Args:
            session:    Live SSHSession connected to the DPU
                        (target="dpu" means the engine built a DPU session).
            variables:  Assembled variable dict — includes join_command from
                        kubeadm-init outputs.
            on_output:  Streaming log callback (line: str) -> None.

        Returns:
            dict with dpu_joined=True and node_name.

        Raises:
            RuntimeError: If join_command is missing or kubeadm join fails.
        """
        t0 = time.monotonic()
        join_command = variables.get("join_command")
        if not join_command:
            raise RuntimeError(
                "join_command is required but was not found in variables. "
                "Ensure bare-metal/kubeadm-init has completed successfully."
            )

        # 1. Reset any previous kubeadm state (allowed to fail — node may be clean).
        on_output("[kubeadm-join] Resetting any previous kubeadm state...")
        session.execute(
            "sudo kubeadm reset -f --cri-socket=unix:///run/containerd/containerd.sock 2>/dev/null || true",
            timeout=60,
        )

        # 2. Get node hostname — used to delete stale node from control plane.
        r = session.execute("hostname", timeout=10)
        node_name = r.stdout.strip() if r.exit_code == 0 else "unknown"

        # 3. Try to delete stale node from control plane via the host.
        #    The DPU doesn't have kubectl access, but we can use the host
        #    session's SSH credentials (available in variables) to reach the
        #    control plane. We use the join_command endpoint to reach the API.
        #    This is best-effort — if it fails, the join may still succeed
        #    if the node was already removed.
        if node_name and node_name != "unknown":
            on_output(f"[kubeadm-join] Removing stale node '{node_name}' from cluster (if exists)...")
            # Build a host SSH session to run kubectl delete node
            from services.bare_metal.ssh_session import SSHSession as HostSSHSession
            try:
                # The DPU session chains through the host — extract host hop
                # from the jumphost chain (last hop before DPU is the host).
                host_chain = session.jumphost_chain or []
                if host_chain:
                    host_hop = host_chain[-1]
                    host_session = HostSSHSession(
                        host=host_hop.get("host", ""),
                        port=host_hop.get("port", 22),
                        username=host_hop.get("username", ""),
                        password=host_hop.get("password"),
                        private_key_content=host_hop.get("private_key_content"),
                        jumphost_chain=host_chain[:-1] if len(host_chain) > 1 else None,
                        connect_timeout=10,
                    )
                    dr = host_session.execute(
                        f"sudo kubectl delete node {node_name} --ignore-not-found=true 2>&1 || true",
                        timeout=30,
                    )
                    on_output(f"[kubeadm-join] Node cleanup: {dr.stdout.strip()}")
            except Exception as e:
                on_output(f"[kubeadm-join] Node cleanup skipped (non-fatal): {str(e)[:80]}")

        # 3b. For dual_dpu_obmc, pin kubelet's --node-ip to the DPU's
        # data-plane VLAN IP so the K8s Node InternalIP matches the
        # subnet on which kubeadm-init advertised the API server.
        # Without this, the DPU's kubelet picks oob_net0 (10.10.10.x)
        # as the node IP, Calico sets up tunnels over the OOB subnet,
        # and inter-node networking fails. Source the IP from
        # dpu_vlans[0].ip (the deploy DPU's first VLAN, e.g.
        # external30/10.10.30.100/24 — matches host's external30
        # at 10.10.30.19/24).
        rshim_source = (variables.get("rshim_source") or "host").lower()
        if rshim_source == "bmc":
            dpu_vlans = variables.get("dpu_vlans") or []
            dpu_node_ip: str | None = None
            for v in dpu_vlans:
                ip_cidr = (v.get("ip") or "").strip()
                if "/" in ip_cidr:
                    candidate = ip_cidr.split("/", 1)[0]
                    if candidate.count(".") == 3:
                        dpu_node_ip = candidate
                        break
            if dpu_node_ip:
                on_output(
                    f"[kubeadm-join] Pinning kubelet --node-ip={dpu_node_ip} "
                    "via /etc/default/kubelet (data-plane VLAN IP for "
                    "dual_dpu_obmc; matches host's cluster_api_ip subnet)"
                )
                r = session.execute(
                    f"echo 'KUBELET_EXTRA_ARGS=--node-ip={dpu_node_ip}' "
                    "| sudo tee /etc/default/kubelet > /dev/null && echo OK",
                    timeout=10,
                )
                if "OK" not in r.stdout:
                    raise RuntimeError(
                        f"Failed to write /etc/default/kubelet on DPU: "
                        f"exit={r.exit_code} stderr={r.stderr[:200]!r}"
                    )
            else:
                on_output(
                    "[kubeadm-join] WARNING: rshim_source=bmc but no usable "
                    f"VLAN IP in dpu_vlans={dpu_vlans!r} — leaving kubelet "
                    "node-ip on autodetect; inter-node networking may fail"
                )

        # 4. Run the join command (with explicit CRI socket for standard containerd).
        #    D-BM2-001: switched from containerd-k8s to standard containerd.service
        on_output("[kubeadm-join] Joining cluster with kubeadm...")
        join_with_cri = f"{join_command} --cri-socket=unix:///run/containerd/containerd.sock"
        r = session.execute(f"sudo {join_with_cri}", timeout=self.timeout)
        if r.exit_code != 0:
            raise RuntimeError(
                f"kubeadm join failed (exit {r.exit_code}):\n"
                f"stdout: {r.stdout[-2000:]}\n"
                f"stderr: {r.stderr[-2000:]}"
            )
        total = time.monotonic() - t0
        on_output(f"[kubeadm-join] Complete — node: {node_name} ({total:.1f}s total)")

        return {"dpu_joined": True, "node_name": node_name, "execution_duration_seconds": round(total, 1)}

    # ------------------------------------------------------------------
    # Shell-path stubs — engine falls back to these only when execute()
    # raises NotImplementedError, which we never do above.
    # ------------------------------------------------------------------

    def apply_commands(self, variables: dict[str, Any]) -> list[str]:
        # Stubbed out — the Python execute() path is always used.
        return []

    def validate_commands(self, variables: dict[str, Any]) -> list[str]:
        return [
            # Verify kubelet is running
            "sudo systemctl is-active kubelet",
        ]

    def parse_apply_output(self, output: str, variables: dict[str, Any]) -> dict[str, Any]:
        # Unused — execute() returns outputs directly.
        return {}
