apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bnk-operator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bnk-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  CONTROL_PLANE_URL: {{ required "controlPlane.url is required" .Values.controlPlane.url | quote }}
  REGISTRATION_TOKEN: {{ required "controlPlane.token is required" .Values.controlPlane.token | quote }}
