{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bnk-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bnk-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.healthPort }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "bnk-operator.selectorLabels" . | nindent 4 }}
{{- end }}
