{{- if .Values.tls.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bnk-operator.fullname" . }}-tls-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bnk-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    {{- .Values.tls.caCert | nindent 4 }}
{{- end }}
